// 示例音乐人数据
export const SAMPLE_ARTISTS = [
  {
    id: 1,
    name: "林夕",
    handle: "@linxi_music",
    bio: "独立音乐人 | 2025巡演筹备中 🎸",
    location: "北京",
    genre: "独立流行",
    avatar: "🎵",
    coverGradient: "from-purple-600 to-blue-600",
    followers: "128.5K",
    monthlyListeners: "45.2K",
    verified: true,
    topTracks: [
      { id: 1, name: "午夜飞行", plays: "1.2M", duration: "3:45" },
      { id: 2, name: "城市边缘", plays: "856K", duration: "4:12" },
      { id: 3, name: "雨后的街", plays: "642K", duration: "3:28" },
    ],
    project: {
      name: "2025全国巡演计划",
      target: 50000,
      raised: 32500,
      investors: 128,
      daysLeft: 15,
      return: "15% 年化",
    },
  },
  {
    id: 2,
    name: "陈默",
    handle: "@chenmo_electronic",
    bio: "电子音乐制作人 | 新专辑制作中 🎹",
    location: "上海",
    genre: "电子",
    avatar: "🎹",
    coverGradient: "from-emerald-600 to-teal-600",
    followers: "89.3K",
    monthlyListeners: "28.7K",
    verified: true,
    topTracks: [
      { id: 1, name: "深海", plays: "2.1M", duration: "4:32" },
      { id: 2, name: "霓虹", plays: "1.5M", duration: "3:56" },
      { id: 3, name: "脉冲", plays: "980K", duration: "5:12" },
    ],
    project: {
      name: "新专辑《午夜飞行》",
      target: 30000,
      raised: 30000,
      investors: 89,
      daysLeft: 0,
      return: "12% 年化",
    },
  },
  {
    id: 3,
    name: "MC 阿龙",
    handle: "@mc_along",
    bio: "地下说唱 | 成都说唱联盟发起人 🎤",
    location: "成都",
    genre: "说唱",
    avatar: "🎤",
    coverGradient: "from-orange-600 to-red-600",
    followers: "45.2K",
    monthlyListeners: "12.3K",
    verified: false,
    topTracks: [
      { id: 1, name: "街头故事", plays: "520K", duration: "3:22" },
      { id: 2, name: " hustle", plays: "380K", duration: "3:45" },
      { id: 3, name: "成都成都", plays: "290K", duration: "4:08" },
    ],
    project: {
      name: "地下说唱联盟",
      target: 20000,
      raised: 8500,
      investors: 45,
      daysLeft: 28,
      return: "20% 年化",
    },
  },
  {
    id: 4,
    name: "小雨",
    handle: "@xiaoyu_folk",
    bio: "民谣歌手 | 用音乐记录生活 🎸",
    location: "杭州",
    genre: "民谣",
    avatar: "🎸",
    coverGradient: "from-yellow-600 to-orange-600",
    followers: "67.8K",
    monthlyListeners: "18.5K",
    verified: false,
    topTracks: [
      { id: 1, name: "西湖雨", plays: "890K", duration: "4:15" },
      { id: 2, name: "江南", plays: "650K", duration: "3:48" },
      { id: 3, name: "乡愁", plays: "420K", duration: "5:02" },
    ],
    project: {
      name: "民谣诗集",
      target: 15000,
      raised: 12000,
      investors: 67,
      daysLeft: 12,
      return: "14% 年化",
    },
  },
  {
    id: 5,
    name: "DJ Nova",
    handle: "@djnova_official",
    bio: "电子音乐 DJ | 音乐节常客 🎧",
    location: "深圳",
    genre: "电子",
    avatar: "🎧",
    coverGradient: "from-pink-600 to-purple-600",
    followers: "156.3K",
    monthlyListeners: "32.1K",
    verified: true,
    topTracks: [
      { id: 1, name: "Sunrise", plays: "3.2M", duration: "6:45" },
      { id: 2, name: "Cyberpunk", plays: "2.1M", duration: "5:32" },
      { id: 3, name: "Neon Lights", plays: "1.4M", duration: "4:18" },
    ],
    project: {
      name: "电子音乐节",
      target: 40000,
      raised: 28000,
      investors: 95,
      daysLeft: 20,
      return: "18% 年化",
    },
  },
  {
    id: 6,
    name: "摇滚老张",
    handle: "@rock_laozhang",
    bio: "摇滚老炮 | 20年音乐路 🤘",
    location: "北京",
    genre: "摇滚",
    avatar: "🎸",
    coverGradient: "from-red-600 to-pink-600",
    followers: "234.1K",
    monthlyListeners: "55.8K",
    verified: true,
    topTracks: [
      { id: 1, name: "青春", plays: "5.6M", duration: "4:22" },
      { id: 2, name: "叛逆", plays: "3.8M", duration: "3:55" },
      { id: 3, name: "自由", plays: "2.9M", duration: "4:45" },
    ],
    project: {
      name: "复出巡演",
      target: 60000,
      raised: 45000,
      investors: 156,
      daysLeft: 8,
      return: "16% 年化",
    },
  },
];

// 示例项目数据
export const SAMPLE_PROJECTS = SAMPLE_ARTISTS.map((artist) => ({
  id: artist.id,
  name: artist.project.name,
  artist: artist.name,
  artistId: artist.id,
  genre: artist.genre,
  location: artist.location,
  image: artist.avatar,
  coverGradient: artist.coverGradient,
  target: artist.project.target,
  raised: artist.project.raised,
  investors: artist.project.investors,
  return: artist.project.return,
  daysLeft: artist.project.daysLeft,
  status: artist.project.raised >= artist.project.target ? "completed" : "active",
  description: `${artist.name}的${artist.project.name}，支持独立音乐人的音乐事业。`,
}));

// 示例博客文章
export const SAMPLE_BLOG_POSTS = [
  {
    id: 1,
    title: "XMUSIC 平台正式上线：让音乐投资变得简单",
    excerpt: "我们很高兴宣布 XMUSIC 平台正式对外开放。现在，任何人都可以投资自己喜欢的独立音乐人...",
    author: "XMUSIC 团队",
    date: "2025-02-20",
    category: "平台动态",
    readTime: "5 分钟",
  },
  {
    id: 2,
    title: "如何评估一个音乐项目的投资价值？",
    excerpt: "投资音乐项目需要关注哪些指标？本文将从粉丝基础、历史表现、团队背景等多个维度为你解析...",
    author: "投资研究团队",
    date: "2025-02-18",
    category: "投资指南",
    readTime: "8 分钟",
  },
  {
    id: 3,
    title: "独立音乐人的融资新选择：Web3 时代的机遇",
    excerpt: "传统唱片公司的模式正在改变。Web3 技术让音乐人可以直接与粉丝和投资人建立联系...",
    author: "行业观察",
    date: "2025-02-15",
    category: "行业洞察",
    readTime: "6 分钟",
  },
  {
    id: 4,
    title: "林夕 2025 巡演项目融资成功案例分析",
    excerpt: "仅用 15 天，林夕的巡演项目就完成了 5 万美元融资目标。让我们看看这个项目成功的关键因素...",
    author: "案例研究",
    date: "2025-02-10",
    category: "成功案例",
    readTime: "10 分钟",
  },
  {
    id: 5,
    title: "加密货币支付指南：如何使用 USDC 投资音乐项目",
    excerpt: "对于初次接触加密货币的用户，本文将详细介绍如何设置钱包、购买 USDC，以及在 XMUSIC 平台上完成投资...",
    author: "产品团队",
    date: "2025-02-05",
    category: "使用教程",
    readTime: "12 分钟",
  },
  {
    id: 6,
    title: "音乐人如何设计有吸引力的融资方案？",
    excerpt: "一个好的融资方案需要明确的目标、合理的估值和清晰的收益分配。本文将为音乐人提供实用的方案设计建议...",
    author: "音乐人支持团队",
    date: "2025-02-01",
    category: "音乐人指南",
    readTime: "7 分钟",
  },
];

// 统计数据
export const PLATFORM_STATS = {
  totalArtists: 156,
  totalProjects: 89,
  totalInvested: "$2.4M+",
  totalInvestors: "3,456",
  avgReturn: "15.8%",
};
